name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  validate:
    name: Validate Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify file structure
        run: |
          for file in includes/class-*.php; do
            if [ ! -f "$file" ]; then
              echo "Missing required file: $file"
              exit 1
            fi
          done

  build:
    name: Create Release
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          mkdir wp-donation-system
          cp -r admin includes templates assets languages *.php *.md wp-donation-system/
          zip -r wp-donation-system.zip wp-donation-system

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog
        run: |
          CHANGELOG=$(awk -v ver="[${{ steps.get_version.outputs.VERSION }}]" '/^## \[/{p=0} $0~ver{p=1} p' CHANGELOG.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
          files: |
            wp-donation-system.zip
            LICENSE
            README.md 